# AWS Secrets pour S3 - À adapter avec vos vraies clés
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: jamaa
type: Opaque
data:
  # Base64 encoded AWS credentials
  aws-access-key-id: AKIAQS7P6FWIA2BCUKPW
  aws-secret-access-key: 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
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: jamaa
data:
  AWS_S3_BUCKET_NAME: "jamaacniupload"
  AWS_S3_REGION: "eu-north-1"
