# AWS Secrets pour S3 - À adapter avec vos vraies clés
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: jamaa
type: Opaque
data:
  # Base64 encoded AWS credentials - REMPLACEZ PAR VOS VRAIES CLÉS
  aws-access-key-id: WU9VUl9BV1NfQUNDRVNTX0tFWV9JRA==
  aws-secret-access-key: WU9VUl9BV1NfU0VDUkVUX0FDQ0VTU19LRVk=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: jamaa
data:
  AWS_S3_BUCKET_NAME: "jamaacniupload"
  AWS_S3_REGION: "eu-north-1"
