# Horizontal Pod Autoscaler pour tous les services
# Auto-scaling basé sur CPU et mémoire

# Service Proxy (Gateway) - Le plus critique
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-proxy-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-proxy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Users - Haute charge attendue
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-users-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-users
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Transfert - Critique pour les transactions
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-transfert-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-transfert
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Transactions - Haute charge pour l'historique
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-transactions-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-transactions
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Account - Opérations fréquentes
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-account-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-account
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Notifications - Peut avoir des pics
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-notifications-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-notifications
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Service Recharge-Retrait - Opérations critiques
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-recharge-retrait-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-recharge-retrait
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Services moins critiques avec scaling modéré
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-auth-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-auth
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-banks-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-banks
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-card-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-card
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-banks-account-hpa
  namespace: jamaa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-banks-account
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
