apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstore-pvc
  namespace: jamaa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore
  namespace: jamaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore
  template:
    metadata:
      labels:
        app: eventstore
    spec:
      containers:
      - name: eventstore
        image: eventstore/eventstore:23.10.0-jammy
        ports:
        - containerPort: 2113
        - containerPort: 1113
        env:
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "1"
        - name: EVENTSTORE_RUN_PROJECTIONS
          value: "All"
        - name: EVENTSTORE_START_STANDARD_PROJECTIONS
          value: "true"
        - name: EVENTSTORE_EXT_TCP_PORT
          value: "1113"
        - name: EVENTSTORE_HTTP_PORT
          value: "2113"
        - name: EVENTSTORE_INSECURE
          value: "true"
        - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
          value: "true"
        - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
          value: "true"
        volumeMounts:
        - name: eventstore-storage
          mountPath: /var/lib/eventstore
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /health/live
            port: 2113
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 2113
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: eventstore-storage
        persistentVolumeClaim:
          claimName: eventstore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: eventstore-service
  namespace: jamaa
spec:
  selector:
    app: eventstore
  ports:
  - name: http
    port: 2113
    targetPort: 2113
  - name: tcp
    port: 1113
    targetPort: 1113
  type: ClusterIP
