apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-users
  namespace: jamaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-users
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
      - name: service-users
        image: noubissie237/jamaa-project-service-users:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://service-config:2370"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-register:8761/eureka/"
        # Configuration RDS AWS
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://jamaa-database.cvkqiow2srth.eu-north-1.rds.amazonaws.com:3306/jamaa_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: password
        # Configuration JPA
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
        # Configuration RabbitMQ
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-users
  namespace: jamaa
spec:
  selector:
    app: service-users
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
---
# Secret pour stocker le mot de passe RDS de manière sécurisée
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: jamaa
type: Opaque
data:
  password: JamaaAdmin-123