apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy
  namespace: jamaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-proxy
  template:
    metadata:
      labels:
        app: service-proxy
    spec:
      containers:
      - name: service-proxy
        image: noubissie237/jamaa-project-service-proxy:latest
        ports:
        - containerPort: 8079
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://service-config:2370"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-register:8761/eureka/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8079
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8079
          initialDelaySeconds: 90
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-proxy
  namespace: jamaa
spec:
  selector:
    app: service-proxy
  ports:
  - port: 8079
    targetPort: 8079
    nodePort: 30079
  type: NodePort