apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: jamaa
type: Opaque
data:
  # Base64 encoded email password - À remplacer par votre mot de passe
  email-password: c3pkaHRqeG5qZHNveG1waA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notifications
  namespace: jamaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-notifications
  template:
    metadata:
      labels:
        app: service-notifications
    spec:
      containers:
      - name: service-notifications
        image: noubissie237/jamaa-project-service-notifications:latest
        ports:
        - containerPort: 8087
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://service-config:2370"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-register:8761/eureka/"
          # Configuration RDS AWS
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://jamaa-database.cvkqiow2srth.eu-north-1.rds.amazonaws.com:3306/jamaa_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: password
        # Configuration JPA ajoutée
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        - name: SPRING_MAIL_HOST
          value: "smtp.gmail.com"
        - name: SPRING_MAIL_PORT
          value: "587"
        - name: SPRING_MAIL_USERNAME
          value: "supp0rt.jamaa@gmail.com"
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notifications-secret
              key: email-password
        - name: SERVICES_USER_URL
          value: "http://service-users:8082/graphql"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8087
          initialDelaySeconds: 90
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-notifications
  namespace: jamaa
spec:
  selector:
    app: service-notifications
  ports:
  - port: 8087
    targetPort: 8087
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: jamaa
type: Opaque
data:
  password: JamaaAdmin-123