apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-register
  namespace: jamaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-register
  template:
    metadata:
      labels:
        app: service-register
    spec:
      containers:
      - name: service-register
        image: noubissie237/jamaa-project-service-register:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-register
  namespace: jamaa
spec:
  selector:
    app: service-register
  ports:
  - port: 8761
    targetPort: 8761
  type: ClusterIP
