apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-proxy
  namespace: jamaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-proxy
  template:
    metadata:
      labels:
        app: service-proxy
    spec:
      containers:
      - name: service-proxy
        image: noubissie237/jamaa-project-service-proxy:latest
        ports:
        - containerPort: 8079
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://service-config:2370"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-register:8761/eureka/"
        # Configuration pour utiliser les services Kubernetes au lieu des pods Eureka
        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
          value: "true"
        - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
          value: "true"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "service-proxy"
        # Force l'utilisation du load balancer Kubernetes
        - name: SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED
          value: "false"
        - name: SPRING_CLOUD_KUBERNETES_ENABLED
          value: "true"
        # Configuration spécifique pour résoudre les noms de services K8s
        - name: SPRING_CLOUD_LOADBALANCER_USE_SERVICE_NAME
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8079
          initialDelaySeconds: 60  # Augmenté pour laisser plus de temps
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8079
          initialDelaySeconds: 120  # Augmenté pour laisser plus de temps
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-proxy
  namespace: jamaa
spec:
  selector:
    app: service-proxy
  ports:
  - port: 8079
    targetPort: 8079
    nodePort: 30079
  type: NodePort