apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-banks-account
  namespace: jamaa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-banks-account
  template:
    metadata:
      labels:
        app: service-banks-account
    spec:
      containers:
      - name: service-banks-account
        image: noubissie237/jamaa-project-service-banks-account:latest
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://service-config:2370"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-register:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/jamaa_banks_account_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "600m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 90
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: service-banks-account
  namespace: jamaa
spec:
  selector:
    app: service-banks-account
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
