name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_HUB_TOKEN }}

      # Service config
      - name: Build Docker image for service-config
        run: docker build -t noubissie237/jamaa-project-service-config:latest ./service-config/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-config:latest


      # Service register
      - name: Build Docker image for service-register
        run: docker build -t noubissie237/jamaa-project-service-register:latest ./service-register/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-register:latest
        

      # Service proxy
      - name: Build Docker image for service-proxy
        run: docker build -t noubissie237/jamaa-project-service-proxy:latest ./service-proxy/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-proxy:latest

      # Service users
      - name: Build Docker image for service-users
        run: docker build -t noubissie237/jamaa-project-service-users:latest ./service-users/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-users:latest
      
      # Service auth
      - name: Build Docker image for service-auth
        run: docker build -t noubissie237/jamaa-project-service-auth:latest ./service-auth/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-auth:latest
      
      # Service banks
      - name: Build Docker image for service-banks
        run: docker build -t noubissie237/jamaa-project-service-banks:latest ./service-banks/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-banks:latest
      
      # Service banks account
      - name: Build Docker image for service-banks-account
        run: docker build -t noubissie237/jamaa-project-service-banks-account:latest ./service-banks-account/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-banks-account:latest
      
      # Service card
      - name: Build Docker image for service-card
        run: docker build -t noubissie237/jamaa-project-service-card:latest ./service-card/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-card:latest
      
      # Service notifications
      - name: Build Docker image for service-notifications
        run: docker build -t noubissie237/jamaa-project-service-notifications:latest ./service-notifications/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-notifications:latest
      
      # Service recharge-retrait
      - name: Build Docker image for service-recharge-retrait
        run: docker build -t noubissie237/jamaa-project-service-recharge-retrait:latest ./service-recharge-retrait/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-recharge-retrait:latest
      
      # Service transactions
      - name: Build Docker image for service-transactions
        run: docker build -t noubissie237/jamaa-project-service-transactions:latest ./service-transactions/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-transactions:latest
      
      # Service transfert
      - name: Build Docker image for service-transfert
        run: docker build -t noubissie237/jamaa-project-service-transfert:latest ./service-transfert/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-transfert:latest
      
      # Service account
      - name: Build Docker image for service-account
        run: docker build -t noubissie237/jamaa-project-service-account:latest ./service-account/.

      - name: Push Docker image to Docker Hub
        run: docker push noubissie237/jamaa-project-service-account:latest